### PR TITLE
Support gitlens & git-graph

### PR DESCRIPTION
**Pull request by elazarcoh**
This adds support for gitlens & git-graph via the toolbar button.
It should be possible to refactor this to support opening it directly from the gitlens view (not sure about git-graph as it's a webview).

### CODE REVIEW

**Review by moshfeu — COMMENTED** [review]
Thanks you very much for this PR, I'm really appreciate your attitude ❤️ 
Some thoughts of mine. I'd love to hear yours.

- Can you add instructions how to use it in git lens and git graph?
- I'm getting error when I'm trying to diff-merge from gitlens - commits section - `Error: Command failed: git diff -U100000 (deleted) -- [the name of the file]` so it goes to the fallback https://github.com/moshfeu/vscode-diff-merge/blob/deea2a04b41647de01954d78166715050379afb6/src/content.ts#L55-L58
- I guess you came up with the parsing mechanizm by debugging the schema of the extension. The thing is, they might change in the future. Do you have an idea how we avoid chasing after their changes (maybe their parsing API is somehow open or can be open) - I hope you understand what I mean.
- Now that there are quite a few different supported schemas and in order to make the code more readable, can you think of a design we can use here? If you think that it shouldn't be part of this PR, I'm ok with that.

**Comment by elazarcoh** [comment]
* Yes, I'll add a section in the README soon.
* Hmm.. not sure what this "(deleted)" means. It should be the commit hash, when it works. I'll try to look it up in the gitlens repo. 
* That's true. Both gitlens & git-graph does not provide an API. We can contact them and ask for exposing an API. In the meanwhile, I can refactor it out, maybe to a dedicated "externalExtensionsIntegration.ts" and the parsing will include error handling which will tell the user to file an issue regarding it. It'll name the extension which changed its format, so it'll be easy to fix.
* If you think the refactoration I suggested above bullet is good, then I'll do it. It would also enable us to add a context menu entry for gitlens.

**Comment by moshfeu** [comment]
Thanks and Purim Same'ach 🤡

**Comment by elazarcoh** [comment]
I think this PR is kind of ready. The remining problems are:
* The `(deleted)` reference. Do you know how does it happen? is the commit you referred had some weirdness?
* Some diff-editors, s.t. comparing different commits, doesn't make sense to have the button I've added, because it only make sense to have it when comparing something with the "working tree" version of the file. 

To address the second bullet, I'm thinking listening to opening editors and adding a `ContextKey` in case the editor is comparing "working tree" file, so in case it compares 2 commits, then we won't show the button. </b>
But I'm thinking adding it as an another PR. 

What do you think?

The only thing left is to add a section in the README, I'll do it soon.

**Comment by moshfeu** [comment]
- I'll re-check the (deleted) thing.
- I wonder if we can detect non working tree comparison based on the paths of the files since neither of them has "real" path but a temp one or something.

**Pull request closed without merging**
